### ISSUE TITLE
Multi-node training

### ISSUE THREAD

**Issue by NobodyHere2024-hash** [NVlabs/EdgeRunner#2]
Hello! I'm thrilled to see the open-source code; it's an excellent piece of work. 
I have a question about multi-node training. You mentioned using slurm, but modifying only the accelerate config file should allow us to extend to multi-machine training directly, right? Or are there some potential issues we should be aware of?

**Comment by ashawkey** [comment]
Hi, thanks for your interest in our work!
Yes, we use the great `accelerate` package, which unifies training code for single-gpu, multi-gpu, and multi-node training. Usually you just need to make sure the multi-node launcher (e.g., slurm) is configured correctly.

**Comment by NobodyHere2024-hash** [comment]
Understood, thank you very much!
