### ISSUE TITLE
About the vocabulary

### ISSUE THREAD

**Issue by Occulte** [NVlabs/EdgeRunner#3]
Thank you for a great job!

In the _models.py_ file, I noticed that the vocab_size is set to _opt.discrete_bins + 3 + 3_ when _opt.meto_backend == 'LR_ABSCO'_. Could you clarify what the additional 6 tokens represent?

Also, in options.py, I saw that the bos, eos, and pad tokens are represented by 1, 2, and 0, respectively. Is there any chance this could conflict with the discrete coordinates of the vertices?

Thanks in advance!

**Comment by ashawkey** [comment]
@Occulte Hi, thanks for your interest!
The first three are PAD, BOS, EOS, then there are three tace type tokens (Left, Right, Begin), and finally the discretized coordinates (0-511, offseted by 6).

**Comment by Occulte** [comment]
> @Occulte Hi, thanks for your interest! The first three are PAD, BOS, EOS, then there are three tace type tokens (Left, Right, Begin), and finally the discretized coordinates (0-511, offseted by 6).

Thank you for getting back to me.
