### ISSUE TITLE
ImportError: cannot import name 'DummyOptim' from 'accelerate.utils'

### ISSUE THREAD

**Issue by l772308126** [NVlabs/EdgeRunner#4]
Exception has occurred: ImportError
cannot import name 'DummyOptim' from 'accelerate.utils' (/home/gem/anaconda3/envs/EdgeRunner/lib/python3.10/site-packages/accelerate/utils/__init__.py)
  File "/home/lyf/2d_to_3d/EdgeRunner/main.py", line 22, in <module>
    from accelerate.utils import DummyOptim, DummyScheduler
ImportError: cannot import name 'DummyOptim' from 'accelerate.utils' (/home/gem/anaconda3/envs/EdgeRunner/lib/python3.10/site-packages/accelerate/utils/__init__.py)

I installed the accelerate==0.34.2 and all the environment settings are following the requirements-lock.txt. How to solve this problem? I use the cuda12.1 and python3.10.

**Comment by ashawkey** [comment]
@l772308126 Hi, thanks for reporting this! I have removed deprecated code related to deepspeed, you can try with the latest code now.

**Comment by l772308126** [comment]
> @l772308126 Hi, thanks for reporting this! I have removed deprecated code related to deepspeed, you can try with the latest code now.

Thanks!
