### ISSUE TITLE
How To Obtain Dataset

### ISSUE THREAD

**Issue by creiser** [NVlabs/EdgeRunner#5]
Hi!

Great work! Could you potentially provide some details on how to download datasets? For instance, I am not sure how to obtain the following files referenced in provider.py:
```
data_list/objaverse_wface.json
data/gobjaverse_280k_index_to_objaverse.json
data/github_cleaned_wface.json
data/github_fbx_wface.json
```

Thank you,
Christian

**Comment by ashawkey** [comment]
@creiser Hi, thanks for your interest! 
Our datasets includes Objaverse and Objaverse-XL, and these are the list of paths. You can directly download the data from their [website](https://objaverse.allenai.org/). We will release the subsets later with the pretrained models.

**Comment by creiser** [comment]
Thank you!
