### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by YUEVII** [NVlabs/EdgeRunner#6]
Hi, thanks for your great work!
When I try using the mesh tokenizer(the given test code), if I choose the backend as "LR_ABSCO" and "LR", it will cause segmentation fault while "CLERS" is OK. I wonder why this problem happens and how could I solve it? Thanks a lot!

**Comment by ashawkey** [comment]
@YUEVII Hi, thanks for your interest in our work! 
Could you give more details, such as the mesh used to test?

**Comment by YUEVII** [comment]
I've already solved it, thanks a lot!

**Comment by qiisun** [comment]
@YUEVII Hi, How do you solve "segmentation fault" issue in tokenization?
